sudo: required
dist: trusty
language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  #- "pypy3"
install:
  - pip install pyusb coverage coveralls pyserial PyYAML tqdm
script:
  - python setup.py build
  - coverage run --source=stcgal setup.py test
  - coveralls
